from skellstools import limpiar, tamaño, ir, esperar, ejecutar, alinear, color, Color

def cuenta_regresiva(funcion):
    print("3 Segundos")
    esperar(1)
    print("2 Segundos")
    esperar(1)
    print("1 Segundos")
    esperar(1)
    print(f"Ejecutando funcion '{funcion}()'")

print("Este texto desaparecera y no sera visualizado")
limpiar()
print("Este texto si sera visible y seguido del process finished aparecera la barra de comandos del usuario")
print("Ahora observa el tamano de tu terminal abierta: ")
print(f"Alto: {tamaño()[0]}")
print(f"Ancho: {tamaño()[1]}")
print("Ahora modificaremos el texto de la primera linea dentro de 3 segundos")
cuenta_regresiva("ir")
ir(0, 0)
print("Como podras observar, este texto se ha sobreescrito en el anterior //")
print("al mover el cursor, tambien cambiara la posicion en el cual aparece la linea de comandos //")
print("Ahora limpiaremos la terminal en 3 segundos")
cuenta_regresiva("limpiar")
print("Ejecutaremos un comando (dir) del sistema con 'ejecutar'")
ejecutar('dir')
print("Ahora repetiremos lo mismo, pero con (tree)")
ejecutar('tree')
print("Como puede observar, literalmente ejecutamos comandos de la terminal")
print("Ahora limpiamos")
cuenta_regresiva('limpiar')
limpiar()
print("Ahora intentaremos centrar texto en 3 formas distintas y cambiaremos su color: \n")
color(Color.CYAN)
print(alinear("Hola Skellent"))
color(Color.AMARILLO)
print(alinear("Hola Skellent", 'der'))
color(Color.BLANCO, Color.AZUL)
print(alinear("Hola Skellent", 'cen'))
color()
print("Y asi hemos terminado de probar las primeras funciones de Skell's Tools")
